### ISSUE TITLE
Optimize the training speed

### ISSUE THREAD

**Issue by chiyuzhang94** [varsha33/LCL_loss#2]
I suggest that you use matrix operations rather than for-loop to construct the [weighted_mask]( https://github.com/varsha33/LCL_loss/blob/5a92a2b618f0e4e0c3ec929a0e42d2733c6247bd/loss.py#L131).

The for-loop is a bottleneck, which slows down the training speed.

**Comment by varsha33** [comment]
thank you for your suggestion!
